const BARCELONA = [
  {
    id: 1,
    productName: "  Barcelona tercera Temporada 2003/2004",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-third-2003-2004.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
  },
  {
    id: 2,
    productName: "  Barcelona tercera Temporada 2006/2007",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-third-2006-2007.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 3,
    productName: "  Barcelona tercera Temporada 2007/2008",
    productDescription:
      "Camiseta deportiva cómoda y estilizada, diseñada con materiales de alta calidad. Ideal para cualquier actividad física, brinda libertad de movimiento y durabilidad. Un clásico atemporal para tu rutina deportiva.",
    imgUrl: "../assets/barcelona/fc-barcelone-third-2007-2008.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 4,
    productName: "  Barcelona tercera Temporada 2008/2009",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-third-2008-2009.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 5,
    productName: "  Barcelona tercera Temporada 2009/2010",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-third-2009-2010.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 6,
    productName: "  Barcelona tercera Temporada 2010/2011",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-third-2010-2011.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 7,
    productName: "  Barcelona tercera Temporada 2011/2012",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-third-2011-2012.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 8,
    productName: "  Barcelona tercera Temporada 2012/2013",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-third-2012-2013.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 9,
    productName: "  Barcelona tercera Temporada 2014/2015",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-third-2014-2015.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 10,
    productName: "  Barcelona tercera Temporada 2015/2016",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-third-2015-2016.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 11,
    productName: "  Barcelona tercera Temporada 2017/2018",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-third-2017-2018.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 12,
    productName: "  Barcelona tercera Temporada 2018/2019",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-third-2018-2019.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 13,
    productName: "  Barcelona tercera Temporada 2020/2021",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-third-2020-2021.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 14,
    productName: "  Barcelona tercera Temporada 2021/2022",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-third-2021-2022.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 15,
    productName: "  Barcelona tercera Temporada 2022/2023",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-third-2022-2023.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 16,
    productName: "  Barcelona Exterior Temporada 2004/2005",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-away-2004-2005.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 17,
    productName: "  Barcelona Exterior Temporada 2006/2007",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-away-2006-2007.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 18,
    productName: "  Barcelona Exterior Temporada 2011/2012",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-away-2011-2012.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 19,
    productName: "  Barcelona Exterior Temporada 2014/2015",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-away-2014-2015.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 20,
    productName: "  Barcelona Exterior Temporada 2015/2016",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-away-2015-2016.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 21,
    productName: "  Barcelona Exterior Temporada 2016/2017",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-away-2016-2017.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 22,
    productName: "  Barcelona Exterior Temporada 2017/2018",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-away-2017-2018.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 23,
    productName: "  Barcelona Exterior Temporada 2018/2019",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-away-2018-2019.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 24,
    productName: "  Barcelona Exterior Temporada 2020/2021",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-away-2020-2021.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 25,
    productName: "  Barcelona Exterior Temporada 2021/2022",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-away-2021-2022.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 26,
    productName: "  Barcelona Exterior Temporada 2021/2022",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-away-2021-2022.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 27,
    productName: "  Barcelona exterior Temporada 2022/2023",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-away-2022-2023.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 28,
    productName: "  Barcelona Casa Temporada 2003/2004",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-home-2003-2004.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 29,
    productName: "  Barcelona Casa Temporada 2004/2005",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-home-2004-2005.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 30,
    productName: "  Barcelona Casa Temporada 2005/2006",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-home-2005-2006.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 31,
    productName: "  Barcelona Casa Temporada 2006/2007",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-home-2006-2007.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 32,
    productName: "  Barcelona Casa Temporada 2007/2008",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-home-2007-2008.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 33,
    productName: "  Barcelona Casa Temporada 2008/2009",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-home-2008-2009.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 34,
    productName: "  Barcelona Casa Temporada 2009/2010",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-home-2009-2010.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 35,
    productName: "  Barcelona Casa Temporada 2010/2011",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-home-2010-2011.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 36,
    productName: "  Barcelona Casa Temporada 2011/2012",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-home-2011-2012.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 37,
    productName: "  Barcelona Casa Temporada 2012/2013",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-home-2012-2013.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 39,
    productName: "  Barcelona Casa Temporada 2014/2015",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-home-2014-2015.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },

  {
    id: 41,
    productName: "  Barcelona Casa Temporada 2016/2017",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-home-2016-2017.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 42,
    productName: "  Barcelona Casa Temporada 2017/2018",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-home-2017-2018.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 43,
    productName: "  Barcelona Casa Temporada 2018/2019",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero, etc.",
    imgUrl: "../assets/barcelona/fc-barcelone-home-2018-2019.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product, barsa, rojo, barcita, barcelona, futbol, soccer, FCB, hombre, masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 44,
    productName: "  Barcelona Casa Temporada 2019/2020",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-home-2019-2020.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 45,
    productName: "  Barcelona Casa Temporada 2020/2021",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-home-2020-2021.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 46,
    productName: "  Barcelona Casa Temporada 2021/2022",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-home-2021-2022.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 47,
    productName: "  Barcelona Casa Temporada 2022/2023",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-home-2022-2023.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
  {
    id: 47,
    productName: "  Barcelona Special 2019/2020",
    productDescription:
      "Producto de alta calidad, con la mejor tela, duradero etc etc etc, super caro tambien, no se que mas poner.",
    imgUrl: "../assets/barcelona/fc-barcelone-special-2019-2020.webp",
    sizes: ["S", "M", "L", "XL", "XXL"],
    pricing: {
      S: 12,
      M: 12.5,
      L: 14,
      XL: 16,
      XXL: 17,
    },
    stock: 20,
    category: "Barcelona",
    productKeywords:
      "Product barsa rojo barcita barcelona futbol soccer FCB hombre masculino",
    generalCategory: "Futbol",
    rating: 4.59,
  },
];

export default BARCELONA;
